### ISSUE TITLE
Getting recognizer's results after scanning only the first side of the card

### ISSUE THREAD

**Issue by yaakovgamliel** [blinkcard/blinkcard-ios#15]
Hi,
We are a happy client of Microblink products (pdf417), currently we are adding capabilities to scan debit/credit cards in our app, our flow does not require the customer to scan the 2 sides of their cards, for several reasons we need the customer to enter their CVV by themselves, is there any way to receive the recognizer's results after scanning the first side of the card.
we run the following version:
iOS iPad supporting everything from iOS 12
`PPBlinkID, '~> 5.9.0'`
`MBBlinkCard, '~> 2.0.0'`

**Comment by Cerovec** [comment]
Hi @yaakovgamliel,

First of all, thanks for using both products. I know this was a big change, moving from our "Custom build" towards separating the SDKs, but I hope it logically makes more sense, using two separate components for two separate problems. Let us know if you have any technical questions regarding this.

As for your question.

It's perfectly fine to have your customers enter CVV by themselves. That's why we added the option to disable scanning of the CVV, as seen in the docs ([link here](https://blinkcard.github.io/blinkcard-ios/Classes/MBCBlinkCardRecognizer.html#/c:objc(cs)MBCBlinkCardRecognizer(py)extractCvv)).

So our advice is to disable the reading of all the fields which are not necessary for your use case, and in that way, it will be much simpler to complete the process for the end-users. I would personally advise disabling everything except Expiry Date (so disabling extractOwner, extractCvv, extractIban). 

In this way, if the PAN and Expiry date are on the same side of the card, the scanning will be done after scanning only the first side of the card. 

Potentially you can enable extractOwner, but then if the Owner name is on the back side of the card, BlinkCard will ask the user to turn the card around. You can experiment and see what makes more sense for your use case.

Hope it makes sense! Let us know if it works or if you encounter any other challenges.

Best,
Jurica.

**Comment by yaakovgamliel** [comment]
Hi Jurica, 
Thank you for your response, keeping IBAN and CVV to `false` did the trick, regarding the SDK being in a separate I'm seeing this error now that both SDKs run together:
```
objc[492]: Class HighpassFilter is implemented in both /private/var/containers/Bundle/Application/1D870D4D-197F-486F-8707-04F169ADE3BB/pos.app/Frameworks/Microblink.framework/Microblink (0x103e38698) and /private/var/containers/Bundle/Application/1D870D4D-197F-486F-8707-04F169ADE3BB/pos.app/Frameworks/BlinkCard.framework/BlinkCard (0x101d4e898). One of the two will be used. Which one is undefined.
objc[492]: Class MGMushParser is implemented in both /private/var/containers/Bundle/Application/1D870D4D-197F-486F-8707-04F169ADE3BB/pos.app/Frameworks/Microblink.framework/Microblink (0x103e39d68) and /private/var/containers/Bundle/Application/1D870D4D-197F-486F-8707-04F169ADE3BB/pos.app/Frameworks/BlinkCard.framework/BlinkCard (0x101d4ff18). One of the two will be used. Which one is undefined.```

Cheers

**Comment by yaakovgamliel** [comment]
Hi Jurica,
It appears that some times after setting both IBAN and CVV extraction to `false`, the SDK still will wait until the card is turned to the other side probably because the name is still required (scanning the name is very important in our flow), does the assigning the `super.metadataDelegates.firstSideFinishedRecognizerRunnerViewControllerDelegate = self` influnce the way the result its taken, I would rather to have a boolean flag to whatever 1 or 2 side of the card is required, in this scenario the SDK will be forced to return after getting all the info it can grab from one side only.

Cheers
